#! /usr/bin/env fish

#! /usr/bin/env nix-shell
#! nix-shell -i fish -p dconf2nix

cd "$(dirname "$0")"

# dconf dump / | dconf2nix > ./modules/home-manager/dconf.nix

echo "# Auto-generated by plasma-manager, do not edit manually!" > ./modules/home-manager/plasma-rc.nix
echo "# See https://github.com/nix-community/plasma-manager" >> ./modules/home-manager/plasma-rc.nix
echo "" >> ./modules/home-manager/plasma-rc.nix
nix run github:nix-community/plasma-manager >> ./modules/home-manager/plasma-rc.nix
