# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  freedownloadmanager = {
    pname = "freedownloadmanager";
    version = "6.24";
    src = fetchurl {
      url = "https://files2.freedownloadmanager.org/6/latest/freedownloadmanager.deb";
      sha256 = "sha256-KZxb7xgLV4riI+A6EIJ5w7gOx/m84+F5JGnUbe4vxs0=";
    };
  };
}
