# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  freedownloadmanager = {
    pname = "freedownloadmanager";
    version = "6.24";
    src = fetchurl {
      url = "https://files2.freedownloadmanager.org/6/latest/freedownloadmanager.deb";
      sha256 = "sha256-rsxMB5RoVmjoSWij1e8kd8Ux0Pl2jSDzzFNx2bO59Wc=";
    };
  };
  github-copilot-app = {
    pname = "github-copilot-app";
    version = "1.1.27";
    src = fetchurl {
      url = "https://github.com/github/app/releases/download/v1.1.27/GitHub-Copilot-linux-x64.deb";
      sha256 = "sha256-E6siamKcrEnq8oFC4Hkydi4EBigSfJxm61vvZIYtWEY=";
    };
  };
}
