# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  freedownloadmanager = {
    pname = "freedownloadmanager";
    version = "6.35.1";
    src = fetchurl {
      url = "https://files2.freedownloadmanager.org/6/latest/freedownloadmanager.deb";
      sha256 = "sha256-3xaIWR6xG/TZBHs8rkS2bXzZd6dlDXmkS5l6LtBc9bA=";
    };
  };
  github-copilot-app = {
    pname = "github-copilot-app";
    version = "1.1.28";
    src = fetchurl {
      url = "https://github.com/github/app/releases/download/v1.1.28/GitHub-Copilot-linux-x64.deb";
      sha256 = "sha256-AZfRCzAftbnH98ZL1VDt/NxsaOHVUi348eAW5IbaTjA=";
    };
  };
}
